-- EXAMCERT FULL SCHEMA FROM LOCAL --

CREATE DATABASE IF NOT EXISTS `examcert` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `examcert`;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `admins` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_name` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role` enum('superadmin','admin') COLLATE utf8mb4_unicode_ci DEFAULT 'admin',
  `last_login` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `cert_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `bg_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `elements` json DEFAULT NULL COMMENT 'array of {id,type,x,y,w,h,content,style}',
  `orientation` enum('L','P') COLLATE utf8mb4_unicode_ci DEFAULT 'L',
  `width_mm` decimal(6,2) DEFAULT '297.00',
  `height_mm` decimal(6,2) DEFAULT '210.00',
  `bg_type` enum('color','image') COLLATE utf8mb4_unicode_ci DEFAULT 'color',
  `bg_color` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT '#FFFFFF',
  `layout_json` json DEFAULT NULL,
  `font_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT 'thsarabun',
  `logo_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `signature_paths` json DEFAULT NULL,
  `show_score` tinyint(1) DEFAULT '0',
  `show_qr` tinyint(1) DEFAULT '1',
  `show_date` tinyint(1) DEFAULT '1',
  `show_name` tinyint(1) DEFAULT '1',
  `show_course` tinyint(1) DEFAULT '1',
  `show_certno` tinyint(1) DEFAULT '1',
  `show_logo` tinyint(1) DEFAULT '1',
  `show_sign1` tinyint(1) DEFAULT '1',
  `show_sign2` tinyint(1) DEFAULT '1',
  `color_primary` varchar(7) COLLATE utf8mb4_unicode_ci DEFAULT '#E87722',
  `preview_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `cert_templates_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `admins` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `projects` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `organizer` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `exam_start` datetime DEFAULT NULL,
  `exam_end` datetime DEFAULT NULL,
  `manual_override` tinyint(1) DEFAULT '0',
  `warning_before` int DEFAULT '30',
  `allow_early_login` tinyint(1) DEFAULT '0',
  `auto_submit_on_close` tinyint(1) DEFAULT '1',
  `pass_score` decimal(5,2) DEFAULT '70.00',
  `max_attempts` int DEFAULT '1',
  `time_limit_min` int DEFAULT '60',
  `question_count` int DEFAULT '0',
  `randomize_questions` tinyint(1) DEFAULT '1',
  `randomize_choices` tinyint(1) DEFAULT '1',
  `show_result_immediately` tinyint(1) DEFAULT '1',
  `cert_template_id` int DEFAULT NULL,
  `cert_number_prefix` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'CERT',
  `cert_sequence` int DEFAULT '1',
  `status` enum('draft','active','closed') COLLATE utf8mb4_unicode_ci DEFAULT 'draft',
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `cert_template_id` (`cert_template_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `projects_ibfk_1` FOREIGN KEY (`cert_template_id`) REFERENCES `cert_templates` (`id`),
  CONSTRAINT `projects_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `admins` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `participants` (
  `id` int NOT NULL AUTO_INCREMENT,
  `project_id` int NOT NULL,
  `title` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `organization` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `position` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_card` varchar(13) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `access_token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `note` text COLLATE utf8mb4_unicode_ci,
  `import_batch` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `access_token` (`access_token`),
  KEY `created_by` (`created_by`),
  KEY `idx_project_name` (`project_id`,`first_name`,`last_name`),
  KEY `idx_token` (`access_token`),
  CONSTRAINT `participants_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `participants_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `admins` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `questions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `project_id` int NOT NULL,
  `question_text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `question_image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` enum('multiple_choice','true_false','fill_blank','subjective','rating_scale') COLLATE utf8mb4_unicode_ci DEFAULT 'multiple_choice',
  `choices` json DEFAULT NULL,
  `correct_answer` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `explanation` text COLLATE utf8mb4_unicode_ci,
  `score_weight` decimal(5,2) DEFAULT '1.00',
  `category` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `difficulty` enum('easy','medium','hard') COLLATE utf8mb4_unicode_ci DEFAULT 'medium',
  `order_num` int DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `project_id` (`project_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `questions_ibfk_1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `questions_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `admins` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `exam_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `participant_id` int NOT NULL,
  `project_id` int NOT NULL,
  `attempt_no` int DEFAULT '1',
  `question_order` json DEFAULT NULL,
  `score` decimal(8,2) DEFAULT '0.00',
  `total_score` decimal(8,2) DEFAULT '0.00',
  `percent` decimal(5,2) DEFAULT '0.00',
  `status` enum('in_progress','submitted','expired') COLLATE utf8mb4_unicode_ci DEFAULT 'in_progress',
  `result` enum('pass','fail') COLLATE utf8mb4_unicode_ci DEFAULT 'fail',
  `started_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `submitted_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `project_id` (`project_id`),
  KEY `idx_participant_project` (`participant_id`,`project_id`),
  CONSTRAINT `exam_sessions_ibfk_1` FOREIGN KEY (`participant_id`) REFERENCES `participants` (`id`),
  CONSTRAINT `exam_sessions_ibfk_2` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `answer_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `session_id` int NOT NULL,
  `question_id` int NOT NULL,
  `given_answer` text COLLATE utf8mb4_unicode_ci,
  `is_correct` tinyint(1) DEFAULT NULL,
  `score_earned` decimal(5,2) DEFAULT '0.00',
  `grading_status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT 'auto',
  `answered_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `session_id` (`session_id`),
  KEY `question_id` (`question_id`),
  CONSTRAINT `answer_logs_ibfk_1` FOREIGN KEY (`session_id`) REFERENCES `exam_sessions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `answer_logs_ibfk_2` FOREIGN KEY (`question_id`) REFERENCES `questions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `certificates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `cert_number` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `participant_id` int NOT NULL,
  `project_id` int NOT NULL,
  `session_id` int NOT NULL,
  `template_id` int NOT NULL,
  `issued_date` date NOT NULL,
  `issued_by` int DEFAULT NULL,
  `file_path` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verify_token` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `verify_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `download_count` int DEFAULT '0',
  `last_downloaded_at` datetime DEFAULT NULL,
  `is_revoked` tinyint(1) DEFAULT '0',
  `revoke_reason` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cert_number` (`cert_number`),
  UNIQUE KEY `verify_token` (`verify_token`),
  KEY `participant_id` (`participant_id`),
  KEY `project_id` (`project_id`),
  KEY `session_id` (`session_id`),
  KEY `template_id` (`template_id`),
  KEY `issued_by` (`issued_by`),
  CONSTRAINT `certificates_ibfk_1` FOREIGN KEY (`participant_id`) REFERENCES `participants` (`id`),
  CONSTRAINT `certificates_ibfk_2` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `certificates_ibfk_3` FOREIGN KEY (`session_id`) REFERENCES `exam_sessions` (`id`),
  CONSTRAINT `certificates_ibfk_4` FOREIGN KEY (`template_id`) REFERENCES `cert_templates` (`id`),
  CONSTRAINT `certificates_ibfk_5` FOREIGN KEY (`issued_by`) REFERENCES `admins` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
